### ISSUE TITLE
CRAN Note

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#104]
We got a note on CRAN: https://cran.r-project.org/web/checks/check_results_simstudy.html
>   'LazyData' is specified without a 'data' directory

Do we need LazyData for anything or is this a remnant from a previous version?

**Comment by kgoldfeld** [comment]
I think this is an R package development thing - I know that a lot of folks are running into this issue (I'm on an R package developers e-mail chain). I actually haven't really paid too close attention as to how it is resolved. But, I never explicitly used LazyData, nor did simstudy include any data sets at any point.

**Comment by assignUser** [comment]
Ah yes I see, it seems to be a new check.
