### ISSUE TITLE
Working with vectorized variables in formulas

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#105]
I was just generating data where I found it useful to vectorize an operation, but I could not get it to work with simstudy. This is just a note in case someone has time to look into this issue.

This is what I was trying to do, which obviously works fine:

```
library(simstudy)
set.seed(1)

d <- defData(varname = "a", formula = 0.6, dist="binary")
d <- defData(d, varname = "b", formula = 0.4, dist="binary")
d <- defData(d, varname = "c", formula = 0.3, dist="binary")
d <- defData(d, varname = "theta", formula = "..tau[1]*a + ..tau[2]*b + ..tau[3]*c", dist = "nonrandom")

tau <- rnorm(3, 0, 1)
tau
#> [1] -0.6264538  0.1836433 -0.8356286

genData(4, d)
#>    id a b c      theta
#> 1:  1 0 0 1 -0.8356286
#> 2:  2 0 0 0  0.0000000
#> 3:  3 0 1 1 -0.6519853
#> 4:  4 1 0 1 -1.4620824
```

But I wanted to simplify the equation for `theta` by vectorizing, defining the formula as `t(..tau) %*% c(a, b, c)`. This returned an error when I tried generating the data:

```
d <- updateDef(d, changevar = "theta", newformula = "t(..tau) %*% c(a, b, c)")

genData(4, d)
#> Error in t(..tau) %*% c(a, b, c): non-conformable arguments
```

However, more generally, this can work as long as no variables are referenced (which obviously is not so useful):

```
d <- updateDef(d, changevar = "theta", newformula = "t(..tau) %*% c(1, 1, 1)")

genData(4, d)
#>    id a b c     theta
#> 1:  1 1 1 1 -1.278439
#> 2:  2 1 1 0 -1.278439
#> 3:  3 1 1 1 -1.278439
#> 4:  4 1 0 0 -1.278439
```

This is really a `data.table` issue, so my guess is we can fix it in `simstudy`. Here is a `data.table` example that generates the same error.

```
d <- d[1:3]
x <- genData(4, d)
x
#>    id a b c
#> 1:  1 0 0 0
#> 2:  2 1 0 1
#> 3:  3 1 1 0
#> 4:  4 0 1 0

x[, t(tau) %*% c(a, b, c)]
#> Error in t(tau) %*% c(a, b, c): non-conformable arguments
```

However, if we execute the formula using `keyby`, it works. So, we might want to make sure we are doing this in `simstudy`:

```
x[, t(tau) %*% c(a, b, c), keyby = id]
#>    id         V1
#> 1:  1  0.0000000
#> 2:  2 -1.4620824
#> 3:  3 -0.4428105
#> 4:  4  0.1836433
```

**Comment by kgoldfeld** [comment]
Just a quick follow-up - I think if we solve this, it would generalize to all functions that use multiple columns as arguments.

**Comment by assignUser** [comment]
Ah interesting, I'll keep that in mind.

**Comment by assignUser** [comment]
This will actually work after #102 is merged :D
