### ISSUE TITLE
Pseudoreplication

### ISSUE THREAD

**Issue by noah472** [kgoldfeld/simstudy#106]
Hi,

Apologies if this is the wrong place to ask this!

I am trying to simulate some data for trials that involve fish. There are two levels of variation that I need to account for, firstly the variance in the tank between the fish and secondly the variance between the tanks but within the treatment. There are  X treatments. Typical coefficient of variance within the tank is 28% on a mean of 1.5 and a variance of 3.2% on the tank mean between X treatments. The fish are typically counted as pseudoreplicates and are thus nested with the replicates within the linear model for analysis.

I cant see any easy way to do this in the vignettes, have i missed something?

**Comment by kgoldfeld** [comment]
This sounds like fairly straightforward clustered data - did you see this [vignette](https://kgoldfeld.github.io/simstudy/articles/clustered.html)? In this case, you would generate tanks (and their random effects), assign the tanks to a treatment arm, and generate fish within the tanks along with the outcome measurement (which will be based on the the tank effect as well as the treatment effect, and random fish variation).

If that isn't what you are describing, maybe it would help to write down the model (which you can use as the data generating process). And if you can't get it going, I might be able to right some simple code.

**Comment by noah472** [comment]
Thanks a lot for coming back to me. I had missed that vignette, sorry.

You are exactly correct with what you are describing. The variation within the tanks gives an overall variation between the tanks of the values in my original post. 
I ran through the vignette and have been able to generate the appropriate data structure for the ind fish, tanks and treatments, however, I am struggling to be able to simulate the data such that it reflects the higher level i.e.  the mean of the individual fish values is not the same as the tank mean. 

This is the script that I have put together:

``` r
set.seed(123)
gen.treatment.mean <- defData(varname = "Treatment_Mean", dist = "normal", formula = 1.5, variance = 0.2, 
                      id = "Treatment")

gen.treatment.mean <- defData(gen.treatment.mean, varname = "nReps", formula = 3)

dtTreat <- genData(5, gen.treatment.mean) #Create number of treatments

gen.Tank.Mean <- defDataAdd(varname = "Replicate", dist = "normal", formula = 1.5, variance = 0.05)
gen.Tank.Mean <- defDataAdd(gen.Tank.Mean, varname = "Fish_Sampled", 
                        formula = 10, variance = 0)

dtTreatandTank <- genCluster(dtTreat, "Treatment", numIndsVar = "nReps", level1ID = "Rep_Number")
dtTreatandTank <- addColumns(gen.Tank.Mean, dtTreatandTank)

gen.ind.fish.values <- defDataAdd(varname = "Individual_Fish", dist = "normal", 
                          formula = 1.5, variance = 0.45)

dtTreatandTankandFish <- genCluster(dtTreatandTank, cLevelVar = "Rep_Number", numIndsVar = "Fish_Sampled", 
                        level1ID = "Treatment")

dtTreatandTankandFish <- addColumns(gen.ind.fish.values, dtTreatandTankandFish)

```

<sup>Created on 2021-09-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kgoldfeld** [comment]
I don't believe you are generating the individual tank and fish outcomes quite right. Right now, the fish data are being drawn from a fixed N(1.5, 0.45) distribution, and the tanks are coming from fixed N(1.5, 0.05). 

The tanks should be drawn from N(mu_j, 0.05), where mu_j is the  j'th`Treatment_Mean` generated when creating the treatment groups:

```r
gen.Tank.Mean <- defDataAdd(varname = "Replicate", dist = "normal", formula = "Treatment_Mean", variance = 0.05)
gen.Tank.Mean <- defDataAdd(gen.Tank.Mean, varname = "Fish_Sampled",  formula = 10, variance = 0)
```

and

the individual fish should be drawn from N(mu_k, 0.45) where mu_k is the k'th tank mean(the field `Replicate`) generated when created replicate tanks within the treatment groups:

```r
gen.ind.fish.values <- defDataAdd(varname = "Individual_Fish", dist = "normal",  formula = "Replicate", variance = 0.45)
```

**Comment by noah472** [comment]
Ok, thanks! That makes a bit more sense. What I am struggling with is being able to derive the individual values such that they add up to the tank values and the tank values across the three reps add up to the treatment value whilst taking into account the variation expected (i.e. within the reps there is 28% variation and between the reps of that treatment there is 3.2% variation and also a definable variation between the treatments i.e. 10%)

For example in the attached image I want to be able to have the values of individual fish that are assigned to Rep_Number 1 to add up to 1.632848 instead they average to 2.39918087 . In this example there is only 4 fish in total and I would like the sum of these to be the treatment mean instead of here where they average 1.249348 instead of 1.49263.

Sorry if this is unclear or obvious. 

<img width="633" alt="Screenshot 2021-09-01 at 21 41 14" src="https://user-images.githubusercontent.com/17271522/131743262-22a394d2-e39e-4016-bf6f-204157f7507d.png">

**Comment by kgoldfeld** [comment]
It would be helpful if you include the code you used to generate the data, so I can replicate what you've done. One of the issues is that you have a very small sample size both in terms of tanks per treatment and fish per tank. This is not necessarily small in terms of your actual experiment, but in terms of expecting the observed data to reflect the underlying data generation assumptions, you might be disappointed simply due to sampling variation. If you share your code with me, I can see if this indeed the case.
