### ISSUE TITLE
Double-dot notation not working in function

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#107]
The issue is that the double dot notation is working inside a function when the variable is specified in the function and is not global.

I thought we had seen this error before, and I thought it had been fixed, because I was certainly able to implement it before. But I recently loaded the latest development version of R, so I am not sure if it is a simstudy problem or an R problem.

```r
library(simstudy)

test <- function(list_of_stuff) {
  
  list2env(list_of_stuff, envir = environment())
  
  print(mu)
  print(n)
  
  dx <- genData(n)
  print(dx)

  dx <- addColumns(def, dx)
  
  print("done")
  
  dx[]
}

def <- defDataAdd(varname = "x1", formula = "..mu", variance = 8, dist = "beta")

test(list(def = def, n = 5, mu = .3))
#> [1] 0.3
#> [1] 5
#>    id
#> 1:  1
#> 2:  2
#> 3:  3
#> 4:  4
#> 5:  5
#> Error: External variable(s) not defined or NA: mu
```

But outside the function it works fine ...

```r
mu <- .3
dx <- genData(5)
dx <- addColumns(def, dx)
dx
#>    id        x1
#> 1:  1 0.3928187
#> 2:  2 0.2182046
#> 3:  3 0.2429830
#> 4:  4 0.3263371
#> 5:  5 0.2677123
```

**Comment by kgoldfeld** [comment]
Here is my R version info - obviously, you can run this exact version unless you have a Mac M1 machine, but think there are versions 4.1.1 for other platforms. I am curious to see if you get the same error.

```r
R.Version()
#> $platform
#> [1] "aarch64-apple-darwin20"
#> 
#> $arch
#> [1] "aarch64"
#> 
#> $os
#> [1] "darwin20"
#> 
#> $system
#> [1] "aarch64, darwin20"
#> 
#> $status
#> [1] ""
#> 
#> $major
#> [1] "4"
#> 
#> $minor
#> [1] "1.1"
#> 
#> $year
#> [1] "2021"
#> 
#> $month
#> [1] "08"
#> 
#> $day
#> [1] "10"
#> 
#> $`svn rev`
#> [1] "80725"
#> 
#> $language
#> [1] "R"
#> 
#> $version.string
#> [1] "R version 4.1.1 (2021-08-10)"
#> 
#> $nickname
#> [1] "Kick Things"
```

**Comment by kgoldfeld** [comment]
I realize that I did not check to see if this is a problem specific to the `beta` distribution, and indeed it is. It works fine when the distribution is `normal` or really anything else. So, it is a `beta` bug.

**Comment by assignUser** [comment]
I just checked and I am pretty sure this was fixed in #98 
Please try it with `devtools::install_github("kgoldfeld/simstudy")` and let me know if the error persists.

**Comment by kgoldfeld** [comment]
Isn't the development version in the "main" branch? I am totally up to date with that, and my latest local build is based on that - so wouldn't I have the updates?

**Comment by kgoldfeld** [comment]
It was my own ridiculous mistake - I was in another branch. Totally works.

**Comment by assignUser** [comment]
Ah don't worry happens to everyone :D
