### ISSUE TITLE
Generating categorical data causes system to crash (in development version only)

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#108]
When I execute the following code in the current development version of `simstudy`, my system crashes. (I've tried rebooting, and the same thing happens again.)

```r
library(simstudy)

d <- defData(varname = "test", formula = "0.4;0.3;0.3", dist="categorical")
genData(10, d)
```
<img width="548" alt="Screen Shot 2021-09-30 at 12 19 24 PM" src="https://user-images.githubusercontent.com/5994273/135493396-ea0406fe-4947-45d2-a5e5-87cfa57b0d7c.png">

However, with the "production" of `simstudy` from `Cran`, everything works fine:

```r
library(simstudy)

d <- defData(varname = "test", formula = "0.4;0.3;0.3", dist="categorical")
genData(10, d)
#>     id test
#>  1:  1    1
#>  2:  2    1
#>  3:  3    1
#>  4:  4    1
#>  5:  5    3
#>  6:  6    2
#>  7:  7    1
#>  8:  8    1
#>  9:  9    2
#> 10: 10    2
```

**Comment by assignUser** [comment]
I tried to replicate this on my pc but it does not happen for me. I really don't see anything in simstudy that could cause this ...

except, maybe its an issue with RCPP and your new M1 Apple thing? Because .gencat calls: `.Call(`_simstudy_matMultinom`, parsedProbs, PACKAGE = "simstudy")`

Does this happen with any other packages?

**Comment by assignUser** [comment]
p.s. you could try to update your version of RCPP (you don't need RTools on mac right?) and install the main branch version again with
`devtools::install_github("kgoldfeld/simstudy")`

**Comment by kgoldfeld** [comment]
Of course, you were right - it was a compiling issue. It turns out, I need this Big Sur M1-specific `gcc` `c++` compiler in `gfortran` which I was able to download from [here](https://github.com/fxcoudert/gfortran-for-macOS/releases). The problem created above has gone away.

**Comment by assignUser** [comment]
Ah good to hear that you could fix it :)
