### ISSUE TITLE
non-balanced randomisation issue

### ISSUE THREAD

**Issue by simonelgato** [kgoldfeld/simstudy#132]
Running this line from one of your examples 

study3 <- trtAssign(dtstudy, n = 3, balanced = FALSE, grpName = "rxGrp")

gives this error message:
Error in trtObserve(dt, formulas = formula, logit.link = FALSE, grpName) : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'

The first two examples (study1 and study2 with stratified and balanced but not stratified randomisation) worked fine, but this one didn't. I'm not expert enough to understand why!

**Comment by assignUser** [comment]
What version of the `Rcpp` package do you have installed? (you can find out with `packageVersion("Rcpp")`)

**Comment by assignUser** [comment]
@simonelgato Could you solve your problem?

**Comment by assignUser** [comment]
@simonelgato  I assume you have solved your problem and am going to close this for now. If you still have this issue feel free to let us know and open the issue back up! :slightly_smiling_face:

**Comment by simonelgato** [comment]
Apols for lack of response - found this in my spam folder. Yes, I solved the issue but can't remember exactly how right now. Thanks for response anyway.
