### ISSUE TITLE
Release simstudy 0.4.0 - the unofficial version

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#137]
@assignUser Any reason not to start getting ready to submit current version to CRAN?

**Comment by assignUser** [comment]
We have no open bug issues so we can get started. It would be 0.4.0 though as the last digit is just for patch/bugfix releases :grin: 
(https://semver.org)

**Comment by kgoldfeld** [comment]
Last time, you had that great checklist - I think the list is much shorter now. Is that something easy to recreate?

**Comment by assignUser** [comment]
I created it using a a [usethis function](https://usethis.r-lib.org/reference/use_release_issue.html):
`usethis::use_release_issue("0.4.0")` 
This require your github authentication to be available but that is usually the case when you can push and pull from the repo without entering your password.

**Comment by kgoldfeld** [comment]
OK - I'll give it a go, and see how it works out.

**Comment by kgoldfeld** [comment]
It seems to have worked just fine. I noticed when you did it last time, it generated a list of issues to address before all the other steps. What issues does it pick up?

**Comment by assignUser** [comment]
I edited the issue manually after creating it with the function and added them. It would be nice though if it would add all issues with a bug tag or which have the correct milestone :D

**Comment by kgoldfeld** [comment]
Yeah – that would be nice – and I assumed it was doing something like that. Maybe you should write that :D
