### ISSUE TITLE
Redundant/ghost code in .isValidArithmeticFormula?

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#139]
@assignUser I am just working through the code to increase the code coverage of our testing. In the function `.isValidArithmeticFormula`, there seems to be some leftover code from an earlier version. The `stop` call seems redundant, and indeed is not covered by the unit tests, though the `valueError` call is covered. I assume that is because when there is an error, the `valueError` gets triggered before it can get to the `stop`. If you confirm, I will remove.

https://github.com/kgoldfeld/simstudy/blob/0733df4957441a7460b9cfe347acc27c716e03f3/R/define_data.R#L821-L833

**Comment by assignUser** [comment]
Yep, that's correct. Nice find :)
