### ISSUE TITLE
genMiss does not work with double dot notation

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#145]
Need to implement double dot notation for the missing data functionality. This will require editing function `.genMissDataMat`.

**Comment by assignUser** [comment]
I am a bit swamped atm, if I have a moment I will take a look :)

**Comment by kgoldfeld** [comment]
I am sure you are swamped - figured you wouldn't get to this anytime soon. I did get something that works. See the branch [double_dot_for_missing](https://github.com/kgoldfeld/simstudy/tree/double_dot_for_missing).

**Comment by kgoldfeld** [comment]
Done
