### ISSUE TITLE
update genMarkov to allow user to specify distribution for starting state

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#146]
Currently the starting state for Markov processes generated by `genMarkov` is category 1. A user has suggested it might be nice to be able to specify a (categorical) distribution that will determine a stochastic set of starting states. This can currently be done with `addMarkov`, but the starting state needs to be generated separately.

**Comment by elinsooon** [comment]
I believe I addressed this but let me know if the implementation isn't quite right

**Comment by kgoldfeld** [comment]
You have made a very nice start - I've made comments in the pull request.

**Comment by kgoldfeld** [comment]
Check now - it looks like I did not submit review ...

**Comment by kgoldfeld** [comment]
Done.
