### ISSUE TITLE
double dot notation in genMiss testing and more generally

### ISSUE THREAD

**Issue by elinsooon** [kgoldfeld/simstudy#160]
In order to test genMiss, I've written the following code. However, in defining the variables for the "x2" column formula (form1val0 and form1val1), eval(parse()) inside of .genMissDataMat is unable to access said variables, since they are outside of its scope. I tried using double-dot, and I tried thinking of ways to define the formula before it gets passed to genMiss so that genMiss doesn't have to evaluate form1val0 and form1val1 itself, but since form1 also includes the variable m which is housed inside of the defMiss data.table, I haven't been able to figure this out coming from that angle either. 

I imagine there's a way around this without an overhaul of the internal code in genMiss.

`def1 <- defData(varname = "m", dist = "binary", formula = .5)
  def1 <- defData(def1, "u", dist = "binary", formula = .5)
  def1 <- defData(def1, "x1", dist="normal", formula = "20*m + 20*u", variance = 2)
  def1 <- defData(def1, "x2", dist="normal", formula = "20*m + 20*u", variance = 2)
  def1 <- defData(def1, "x3", dist="normal", formula = "20*m + 20*u", variance = 2)
  
  dtAct <- genData(5000, def1)
  
  hardProbForm <- runif(1)
  form1val0 <- runif(1)
  form1val1 <- runif(1)
  form1 <- "form1val0*(1-m) + m*form1val1"
  
  defM <- defMiss(varname = "x1", formula = hardProbForm, logit.link = FALSE)
  defM <- defMiss(defM, varname = "x2", formula = form1, logit.link = FALSE)
  defM <- defMiss(defM, varname = "u", formula = 1, logit.link = FALSE) # not observed
  
  missMat <- genMiss(dtAct, defM, idvars = "id")`

**Comment by kgoldfeld** [comment]
I believe you need to use double dot notation. So,

```
form1 <- "..form1val0*(1-m) + m*..form1val1"
```

**Comment by kgoldfeld** [comment]
Sorry - you tried that. But, it worked for me.

**Comment by elinsooon** [comment]
double dot didn't work, but I just used paste0() before passing it in to genMiss and it works fine

**Comment by kgoldfeld** [comment]
I'll take a look at the code. But, it should work with double dot notation - if not, that is a bug. This works for me:

```
def1 <- defData(varname = "m", dist = "binary", formula = .5)
  def1 <- defData(def1, "u", dist = "binary", formula = .5)
  def1 <- defData(def1, "x1", dist="normal", formula = "20*m + 20*u", variance = 2)
  def1 <- defData(def1, "x2", dist="normal", formula = "20*m + 20*u", variance = 2)

  dtAct <- genData(5000, def1)
  
  hardProbForm <- runif(1)
  p1 <- runif(1)
  p2 <- runif(1)
  form1 <- "..p1 * (1-m) + m * ..p2"

  defM <- defMiss(varname = "x1", formula = hardProbForm, logit.link = FALSE)
  defM <- defMiss(defM, varname = "x2", formula = form1, logit.link = FALSE)
  defM <- defMiss(defM, varname = "u", formula = 1, logit.link = FALSE) # not observed
  
  
  missMat <- genMiss(dtAct, defM, idvars = "id")
  
  missMat[dtAct$m == 0, mean(x2)]
  missMat[dtAct$m == 1, mean(x2)]
```

**Comment by elinsooon** [comment]
This is the error I get when running that code:

Error in ``[.data.table`(dtName, , eval(Formula))`: Variable 'p1' is not found in calling scope. Looking in calling scope because this symbol was prefixed with .. in the j= parameter.
Backtrace:
 1. simstudy::genMiss(dtAct, defM, idvars = "id")
      at test-missing_data.R:64:2
 2. simstudy::.genMissDataMat(dtName, dtTemp, idvars, tmDefs[i, ])
      at simstudy/R/missing_data.R:122:6
 4. data.table:::`[.data.table`(...)
      at simstudy/R/missing_data.R:292:4
 5. [ base::eval(...) ] with 1 more call
 8. data.table:::`[.data.table`(dtName, , eval(Formula))

**Comment by kgoldfeld** [comment]
So - if you run this in a new session of Rstudio - you get an error?

```
library(simstudy)

set.seed(2872)

def1 <- defData(varname = "m", formula = 0, variance = 1, dist = "normal")
dtAct <- genData(10000, def1)

p0 <- runif(1)
p0
#> [1] 0.08441443

defM <- defMiss(varname = "m", formula = "..p0", logit.link = FALSE)

missMat <- genMiss(dtAct, defM, idvars = "id")

missMat[, mean(m)]
#> [1] 0.0822

```

**Comment by elinsooon** [comment]
No, that runs totally fine

**Comment by kgoldfeld** [comment]
That's good - so we know double-dot does work, at least one condition. How about this in a new session of Rstudio (this is basically your code):

```
library(simstudy)
library(testthat)

def1 <- defData(varname = "m", dist = "binary", formula = .5)
def1 <- defData(def1, "u", dist = "binary", formula = .5)
def1 <- defData(def1, "x1", dist="normal", formula = "20*m + 20*u", variance = 2)
def1 <- defData(def1, "x2", dist="normal", formula = "20*m + 20*u", variance = 2)

dtAct <- genData(5000, def1)

hardProbForm <- runif(1)
form1val0 <- runif(1)
form1val1 <- runif(1)
# form1 <- paste0(form1val0, "*(1-m) + m*", form1val1)
form1 <- "..form1val0 * (1-m) + m * ..form1val1"

defM <- defMiss(varname = "x1", formula = "..hardProbForm", logit.link = FALSE)
defM <- defMiss(defM, varname = "x2", formula = form1, logit.link = FALSE)

missMat <- genMiss(dtAct, defM, idvars = "id")

## check probabilistic column has correct distribution

hardProbAct <- mean(missMat[, x1])
hPDiff <- abs(hardProbAct - hardProbForm)

expect_true(hPDiff < 0.02)

mIs0 <- dtAct[, m == 0]
mIs1 <- dtAct[, m == 1]

missMat0 <- missMat[mIs0]
missMat1 <- missMat[mIs1]

avg0 <- mean(missMat0[, x2])
avg1 <- mean(missMat1[, x2])
```

**Comment by elinsooon** [comment]
It runs fine as well

**Comment by kgoldfeld** [comment]
I think it must be an environment issue - the testthat environment must be funky. Are you familiar with environments in R? Definitely good to understand. You might want to see if there are any other tests that use double dot notation - maybe they will provide some insight?

**Comment by elinsooon** [comment]
I'm not familiar, I'll take a look

**Comment by kgoldfeld** [comment]
So, I'm not actually sure if double dot notation was explicitly implemented for `genMiss`, but it seems to be working because it is a feature of `data.table` which I was not familiar with. (See bullet point (g) [here](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html) for why it seems to works). I wonder if @assignUser (Jacob) recalls whether this was intentional. In any case, we might want to formally implement the double dot option for `genMiss`, which would deal with the environment issue. I'll add an issue to add that feature.

**Comment by elinsooon** [comment]
There's a couple other test files that use double-dot (internal-utility, generate-data

**Comment by elinsooon** [comment]
I see, so then why is it that it doesn't work at all for me? Still an environment issue?

**Comment by elinsooon** [comment]
Oh yes that's what you said

**Comment by kgoldfeld** [comment]
Yes - it works for both us outside the `testthat` context. But once it is run under `testthat`, the environment becomes an issue. If you see other examples where a double dot variable is referenced in a test, there is an explicit creation of an environment. However, the solution here might be different, because as I mentioned earlier (above), I don't think double dot notation was really implemented for `genMiss` and only works because by some weird coincidence, `data.table` now has its own double dot functionality.

**Comment by assignUser** [comment]
Yes the double-dot was inspired by the system used in data.table, interesting to see what consequences that has :D
And yes I only ever implemented double-dot for the distributions and not for any of the utility functions like genMiss.

We had similar issues with testthat when I created double-dot initially, to solve it we pass in the calling argument as due to the way environments inherit parents it is possible to have them in parallel and then the variables are invisible, as R only checks the parents.

**Comment by elinsooon** [comment]
I can give implementing it a shot. I had two thoughts on how to do it. One is to mirror how it's done in the dist functions, which would be by using .evalWith inside of .genMissDataMat. The other idea is to maybe make a slightly different version of .evalWith in the utility functions which instead of fully evaluating the function, just returns a new function with the double-dot variables pasted in, i.e.:
```
x <- 2
y <- 3  
form1 <- "..x*5.5 + ..y*(1-..x)"  
.evalForm(form1)  
<-- "2*5.5 + 3*(1-2)"
```
This would then be passed as normal into .genMissDataMat. This idea is somewhat similar to something I tried with genFormula a little while ago if you remember that @kgoldfeld.

If you have any thoughts on which might be better to try let me know. If I manage to implement one of them I'll commit it and you can take a look.

**Comment by elinsooon** [comment]
I just realized there's already an issue open for this haha, #145, and @kgoldfeld it looks like you already got some code working for this issue too.

**Comment by elinsooon** [comment]
Your code solved all errors on my end

**Comment by kgoldfeld** [comment]
That is a little embarrassing - I guess I've got too much going on. Thanks for finding that. I'll check out what you've done tomorrow.

**Comment by elinsooon** [comment]
Sure thing and sounds good. You have your own branch with this code in it, but I incorporated it into mine as well so it's in the pull request I have open

**Comment by kgoldfeld** [comment]
This has largely been completed.
