### ISSUE TITLE
Parse distribution moments as inputs

### ISSUE THREAD

**Issue by gabgilling** [kgoldfeld/simstudy#166]
I'm interested in using a variable's moments (especially mean or std. dev) as an input to some other variable's data generation process.

Let's say I want to simulate a loan approval based on someone's income.
The base probability of getting an approved loan is 50%, and this increases/decreases based on a person's income expressed as a z-stat, something like:

```r
def <- defData(varname = "income", dist = "normal", formula = 1000,
               variance = 250)
def <- defData(varname = "approval", dist = "binary", formula = "0.5 + 0.1 * z-stat(income))
```

An alternative is to express income as a z-stat / standard normal directly, but a function to do that in simstudy with raw data directly would be neat.

**Comment by kgoldfeld** [comment]
This is interesting. It would represent a different fundamental understanding of the of formula, as the argument income is the entire vector (rather than a row-specific value). I know we have talked about making the formula definition more flexible, and this may be one of those cases.

**Comment by kgoldfeld** [comment]
@gabgilling I know this is about two years too late, but I recently added functionality allow for [customized](https://kgoldfeld.github.io/simstudy/articles/customdist.html) functions. I wasn't thinking of your use case when I created it, but I thought I'd see if it would work here. It does work, but is not quite as elegant as you might have wanted. It requires the user to write a function to that standardizes the data, which is used to generate the standardized files. These standardize values are used to generate the binary outcome:

```{r}
zstat <- function(n, a) {
  scale(a)
}

def <- 
  defData(varname = "income", dist = "normal", formula = 1000, variance = 250) |>
  defData(varname = "z_income", dist = "custom", formula = "zstat", variance = "a = income") |>
  defData(varname = "y", dist = "binary", formula = "0.5 + 0.1 * z_income")

dd <- genData(1000, def)

dd
#> Key: <id>
#>          id    income    z_income     y
#>       <int>     <num>       <num> <int>
#>    1:     1 1018.5090  1.19522736     1
#>    2:     2 1007.0600  0.46026573     1
#>    3:     3  989.1146 -0.69172231     0
#>    4:     4 1032.4047  2.08724599     1
#>    5:     5 1000.2611  0.02381621     0
#>   ---                                  
#>  996:   996 1011.6279  0.75349655     0
#>  997:   997 1012.3793  0.80173291     0
#>  998:   998  982.6470 -1.10690851     1
#>  999:   999 1006.3818  0.41673058     0
#> 1000:  1000  981.7727 -1.16303534     0

dd[, .(mean(z_income), sd(z_income))]
#>              V1    V2
#>           <num> <num>
#> 1: 6.987988e-14     1
```

Let me know what you think.
