### ISSUE TITLE
Survival analysis Weibull parametrisation

### ISSUE THREAD

**Issue by momozinho** [kgoldfeld/simstudy#169]
Hi,

I would be interested in using your package to simulate survival data (esp. the new feature for competing risks).

Unfortunately, I am really struggling with the parametrisation of the Weibull distribution mentioned in the [documentation](https://cran.r-project.org/web/packages/simstudy/vignettes/survival.html).

As it is different from the `rweibull` in R's "Weibull {stats}", I have tried to "translate" from the Wikipedia page which describes 3 different ways. So I figured out that `nu` is `1/shape_rw` where the suffix `_rw` indicates it is the same as in the `rweibull` parametrisation.

But I can't seem to find the equivalent for `nu` (or scale). When `nu`is set to 1, the  distributions seem to align

```r
t <- 0:250
shape <- 1.5
scale <- 80

# function for pdf from simstudy vignette
pdf_simsurv <- function(t, lambda, nu) {
  ((t^((1/nu) - 1))/(lambda * nu)) * exp(-((t^(1/nu))/lambda))
  }

# function for pdf from rweibull
pdf_standard <- function(t, scale, shape) {
  (shape/scale) * ((t/scale)^(shape - 1)) * exp(-((t/scale)^shape))
  }

# when nu is set to 1, both plots exhibit a nice exponential distribution
plot(pdf(t, lambda = scale, nu = 1))
plot(pdf_standard(t, scale = scale, shape = 1))

# but when I input a different value, the shapes are very different
plot(pdf(t, lambda = scale, nu = 1/shape))
plot(pdf_standard(t, scale = scale, shape = shape))

```

I would really appreciate your help!

Best wishes,

Mo

**Comment by kgoldfeld** [comment]
Mo - 

Thanks for getting in touch. You should feel free to e-mail me directly at keith.goldfeld@nyulangone.org. 

If you haven't seen this []([discussion](https://www.rdatagen.net/post/2022-02-08-simulating-survival-outcomes-setting-the-parameters-for-the-desired-distribution/),) take a look - maybe it will help. It includes a [reference](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.2059) that might be even more helpful.

If that doesn't help, let me know.

- Keith

**Comment by momozinho** [comment]
Hi Keith,

Many thanks for this.

I was able to find the `rweibull` equivalent of the scale and shape parameters from the standardisation you used:

```r
t <- 0:250
shape <- 1.5
scale <- 80

# function for pdf from simstudy vignette
pdf_simsurv <- function(t, lambda, nu) {
  ((t^((1/nu) - 1))/(lambda * nu)) * exp(-((t^(1/nu))/lambda))
}

lambda <- scale^shape
nu <- 1/shape

plot(pdf_simsurv(t, lambda = lambda, nu = nu))

# function for pdf from rweibull
pdf_standard <- function(t, scale, shape) {
  (shape/scale) * ((t/scale)^(shape - 1)) * exp(-((t/scale)^shape))
  }

plot(pdf_standard(t, scale = scale, shape = shape))

```

Works perfectly!

Mo
