### ISSUE TITLE
catProbs should warn when adjusting probabilities

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#17]
I know it is clearly stated in the documentation but it has caused silent bugs/issues in my simulatons when catProbs adds a category or normalizes the values due to a  typo. A warning would have saved me time debugging 😄

**Comment by kgoldfeld** [comment]
Sorry about that.

________________________________

**Comment by assignUser** [comment]
😆  no worries

**Comment by assignUser** [comment]
There is also a bug I found via testing that is caused by using `==` instead of `all.equal` combined with the order the conditions are checked a superflous, very tiny extra category is added (`1.11e-16`) due to float inaccuracies. See [R FAQ 7.31](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f). Already working on a fix.

**Comment by assignUser** [comment]
Closed by #22
