### ISSUE TITLE
skip_on_cran() conflicting with covr

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#170]
@assignUser I am trying to understand how and when we should be using  `skip_on_cran()` in the unit testing. I noticed that it is used sometimes, but not always. 

I have found that if `skip_on_cran()` is called, the `covr` report does not pick it up. I know there is a way around this (see [here](https://github.com/r-lib/covr/issues/77), for example), but was wondering why we are using it at all.

**Comment by assignUser** [comment]
In simstudy we skip only long running tests IIRC. So the {hedgehog} property based tests basically.

**Comment by assignUser** [comment]
The {hedgehog} tests take much longer to run then the other tests and they use quite a bit of memory due to the amount of cases they test. With how sensitive CRAN is to such stuff it is just easier to skip them :)

**Comment by kgoldfeld** [comment]
And how to deal with the `covr` issue not working well with `skip_on_cran()` - maybe that workaround would help?
