### ISSUE TITLE
trtAssign fails when strata has count of one

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#19]
`trtAssign`  generates an error when a strata level has a count of one. The following snippet will generate an error:

```
dx <- data.table(x = rep(c(0, 1, 0 ,1), times = c(7, 1, 4, 4)),
                 y = rep(c(0, 1), each = 8))

dx <- trtAssign(dx, strata = c("x", "y"))
```

Surprisingly, this does not generate an error:

```
dx <- data.table(x = rep(c(0, 1, 0 ,1), times = c(1, 7, 4, 4)),
                 y = rep(c(0, 1), each = 8))

dx <- trtAssign(dx, strata = c("x", "y"))
```

**Comment by assignUser** [comment]
Ok, the issue is within `.stratSamp` it returns a vector of **atleast** `length(ncat)` even if that is more than the number of rows to assign.

**Comment by assignUser** [comment]
Not sure why the second does not cause this issue...

**Comment by assignUser** [comment]
Uh... wat?
![image](https://user-images.githubusercontent.com/16141871/95098719-55d7de80-072f-11eb-8234-cfaa30a3fb7f.png)

**Comment by assignUser** [comment]
oh boy it gets weirder: 
![image](https://user-images.githubusercontent.com/16141871/95098851-7c961500-072f-11eb-9c01-d713a476d28a.png)

**Comment by kgoldfeld** [comment]
When nrow is 1 - then the floor argument is 0, and that where things go awry. If nrow == 1, then basically doesn't need to be any stratitifcation.

I believe that if we change this it will work.

```r
neach <- max(floor(nrow / sum(ratio)), 1)
```

**Comment by assignUser** [comment]
I know what the issue is, my wife's input was invaluable :D 
`sample(c(integer(0), 2) == sample(2)` which is shorthand for `sample(1:2)`
The zero length int is the result of `rep(c(1:ncat), times = (neach * ratio))`
I will push a fix soon.
