### ISSUE TITLE
Ready for R 4.0

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#20]
https://cran.r-project.org/doc/manuals/r-devel/NEWS.html

Do we need to change anything?

>Functions rbinom(), rgeom(), rhyper(), rpois(), rnbinom(), rsignrank() and rwilcox() which have returned integer since R 3.0.0 and hence NA when the numbers would have been outside the integer range, now return double vectors (without NAs, typically) in these cases.

This sounds (minorly) interesting?
>stopifnot() now allows customizing error messages via argument names,

**Comment by assignUser** [comment]
@kgoldfeld  We could use the new option for `stopfifnot` for better error messages without custom code but it would require us to depend on R >= 4.0 which I think is not worth it?

**Comment by kgoldfeld** [comment]
Yeah - I don't think we can require R >= 4.0 at this point. We might lose a lot of potential users.

**Comment by assignUser** [comment]
Agreed.
