### ISSUE TITLE
double dot notation not working properly in genSurv

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#202]
When `genSurv` is called in a function using a data definition that has a double-dot reference, the request fails. The issue, I believe, is that the environment is not properly set. For example, a current call is

```r
shape <- as.vector(.evalWith(formshape, .parseDotVars(formshape), dtSurv))
```

but may need to be

```r
shape <- as.vector(.evalWith(formshape, .parseDotVars(formshape, envir), dtSurv))
```

where *envir* has been set in `genSurv`

**Comment by assignUser** [comment]
#203
