### ISSUE TITLE
genBlockMat() function doesn't exist

### ISSUE THREAD

**Issue by ecohen13** [kgoldfeld/simstudy#224]
In following the example for generating clustered data with marginal correlations as outlined here: https://www.rdatagen.net/post/2022-11-22-generating-cluster-data-with-marginal-correlations/

The function genBlockMat() does not seem to exist. It is called in the section for generating data with multiple time periods and repeated individual measures. 

```r
devtools::install_github("kgoldfeld/simstudy")
library(simstudy)
R <- genBlockMat(rho =c(0.3, .1), nInds = 3, nPeriods = 2, iRho = 0.5)
```
Has this been renamed as blockDecayMat()? In the file generate_correlated_data.R line 900 the genBlockMat() function is referenced but on line 970 blockDecayMat() is defined. The arguments passed to blockDecayMat() seem different than in the genBlockMat() example code.

Thanks!

**Comment by kgoldfeld** [comment]
Yes - I never implemented `genBlockMat` but did add `blockExchangeMat` and `blockDecayMat`. Maybe this follow-up [post](https://www.rdatagen.net/post/2023-02-21-flexible-correlation-generation-revisiting-block-matrices-for-temporal-patterns-in-simstudy/) will clarify things.

**Comment by ecohen13** [comment]
Got it, thanks!
