### ISSUE TITLE
Use formula to simulate categorical variable

### ISSUE THREAD

**Issue by lorenzoFabbri** [kgoldfeld/simstudy#228]
I am working on a simulation study for which I need to known the treatment generating mechanism. That is, given a set of variables, I want to simulate the treatment variable based on a known parametric form:

```r
def <- simstudy::defData(
    varname = "variable1",
    dist = "categorical",
    formula = "0.2;0.5;0.3",
    variance = "low;middle;high"
  )
  def <- simstudy::defData(
    dtDefs = def,
    varname = "variable2",
    dist = "normal",
    formula = 35,
    variance = 15
  )
def <- simstudy::defData(
    dtDefs = def,
    varname = "treatment",
    dist = "categorical",
    formula = "variable1 + log(variable2)",
    variance = "level1;level2;level3"
  )
```

To the best of my knowledge, this is not possible since for `formula` I need to pass the probabilities of each level. Is there a workaround? I need to know how the treatment was generated to test some estimators, so I'd do something along the lines of:

```r
mod <- glm(formula = variable1 + log(variable2))
```

I believe I'd have to obtain the probabilities for each level given a multinomial model, but I ask for confirmation.

**Comment by kgoldfeld** [comment]
Lorenzo - I am not fully clear on what the treatment assignment mechanism is. Can you describe the probabilities of treatment assignment with an equation (as a function of variable 1 and variable 2)? Or in words. Feel free to e-mail me directly at keith.goldfeld@nyulangone.org.

**Comment by lorenzoFabbri** [comment]
I apologize!

Let's assume that we have two confounding variables, $C1$ and $C2$. The treatment variable is $X$ and it has 3 levels, and the treatment generating mechanism is given by $X \sim C1 + log(C2)$. So if we wanted to model $X$, and if we were to know the treatment generating mechanism, we would fit a model $X \sim C1 + log(C2)$ (for instance with a multinomial logistic model). So I'd like to generate a categorical variable using the `formula` $C1 + log(C2)$. I hope now it's clear! Thank you.

**Comment by lorenzoFabbri** [comment]
This is probably what I need, thank you. I do have some questions now. In the example, you:

* Define a variable with a binary distribution with an identity link and one with a logit link. I do know the differences between the links, but it is not clear to me what type of variable you want to simulate with a binary distribution and a identity link.
* Define a categorical variable with a logit link. From the documentation it does not seem to be supported.

**Comment by assignUser** [comment]
```r
 # Generate exposure given confounders
  def <- simstudy::defData(
    dtDefs = def,
    varname = "exposure",
    dist = "categorical",
    link = "logit",
    formula = "1 + 0.1*sex*age + 0.5*I(age^2) - 1.3*eth + 0.7*edu + 0.2*sep + 0.3*log(weight);
               -1.3 + 0.3*sex*age + 0.5*I(age^2) - 1.7*eth + 0.7*edu + 0.2*sep + 0.9*log(weight)"
  )
 ```
Your definition for the categorical formula only provides 2 probabilities where as the definition in the blog post has 3: 
```r
defY <- defDataAdd(defY, varname = "y", 
  formula = "b_j - 1.3 + 0.1*A - 0.3*x1 - 0.5*x2 + .55*A*period;
             b_j - 0.6 + 1.4*A + 0.2*x1 - 0.5*x2;
             -0.3 - 0.3*A - 0.3*x1 - 0.5*x2 ", 
  dist = "categorical", link = "logit")
```
See also https://kgoldfeld.github.io/simstudy/articles/simstudy.html#categorical

**Comment by lorenzoFabbri** [comment]
Thank you but in the example, `Y` has four levels. I understood we have to provide `K-1` formulas if the variable has `K levels.

**Comment by kgoldfeld** [comment]
Let me jump back in. If you provide 2 probabilities that sum up to less than 1, a third category is automatically added - so two probabilities can in fact lead to 3 categories. The problem you are having is that both of your probabilities are actually 1 (if you look at the formulas you specified and take the inverse logit, you will see why). Since both are 1, the data generation actually is assigning 50% probability to the two outcomes.

And good catch on the documentation. Categorical data can be defined with the *logit* link.

**Comment by lorenzoFabbri** [comment]
> Let me jump back in. If you provide 2 probabilities that sum up to less than 1, a third category is automatically added - so two probabilities can in fact lead to 3 categories. The problem you are having is that both of your probabilities are actually 1 (if you look at the formulas you specified and take the inverse logit, you will see why). Since both are 1, the data generation actually is assigning 50% probability to the two outcomes.
> 
> 
> 
> And good catch on the documentation. Categorical data can be defined with the *logit* link.

Okay makes sense. I apologize for this basic question, but with such complex generating mechanisms (especially for variables with many levels), how can we make sure that the sum of the probabilities is indeed 1?
