### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#26]
I would propose that we use the [tidyverse style guide](https://style.tidyverse.org/) just with camelCase instead of snake_case.

Let me know what you think @kgoldfeld  :)

**Comment by assignUser** [comment]
We can use [lintr](https://github.com/jimhester/lintr) and [styler](https://github.com/r-lib/styler) to automate the process, so we don't have to activley think about it too much. :)

**Comment by kgoldfeld** [comment]
I think this sounds good.

**Comment by assignUser** [comment]
Ok once we finalize the branch structure I will look into setting that up.

**Comment by assignUser** [comment]
We should keep in mind when switching to snake_case that changing function param names would be a breaking change!

**Comment by assignUser** [comment]
I added the information to the contribution guide. I will add a .lintr file to the dev branch with the correct settings (camelCase, rest tidy style).
