### ISSUE TITLE
consolidate .R files into new structure

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#27]
Changing the file structure should not have any impact on the compiled package, as the function names etc. remain the same (because there are no .R files in a packed package anyway).

In light of this I have written up a new structure that could serve as a  basis. After implementing something like this we can see how work feels and if we want to adjust further.

int_util.R
    - all general utility functions like .isError etc.

util.R
    - utility functions like trimData

generate_data.R 
    - all gen* functions related to data generation 

int_generate_data.R 
    - all internal gen** functions related to data generation
    
generate_util.R 
    - gen* related helper functions like e.g. betaGetShapes

define.R
    - def* functions

add.R
    - add* functions

update.R
    - update* functions

treatments.R
    - trt* functions
    - maybe all "treatment" simulation related functions should move here too? like addPeriods, genObs, defSurv etc.?

splines.R
    - all spline related functions

**Comment by kgoldfeld** [comment]
I think this is a good approach. Would like to have separate .R file for the missing data functions: defMiss, genMiss, genObs. We might also want to separate out the cluster/longitudinal data generation - genCluster, addPeriods, genNthEvent, and maybe trtStepWedge. Do you want to create a list with a mapping, and I will edit - or do you want me to take the first crack at it?

**Comment by assignUser** [comment]
That sounds good, I still don't know all functions perfectly, so it makes sense that you formulate the first version :)

**Comment by kgoldfeld** [comment]
I've created a csv file that is located in a new File_management folder that has a list of existing functions, the current .R file, and a proposed grouping. It is not final, of course - you are free to suggest/make changes.

**Comment by assignUser** [comment]
Looks good I think :) I would just like to change data_generation to generate_data so it follows the same form as define_data and correlated_data but that's just a bit pedantic of me xD I will get to work on this, we can see afterwards how we like it :) and apply any changes.

**Comment by kgoldfeld** [comment]
I will leave the naming to you - I was just focused on the grouping. And feel free to adjust the groups if something seems to fit better somewhere else, or even add a group.

**Comment by assignUser** [comment]
Alright :D I think the groups make sense like this for now 👍

kgoldfeld <notifications@github.com> schrieb am Fr., 7. Aug. 2020, 15:38:

**Comment by assignUser** [comment]
Finished in ee84e15

**Comment by assignUser** [comment]
I moved `.genMissMat` into `missing_data.R` I feel the missing theme binds stronger than that the function generates something
