### ISSUE TITLE
new branch structure

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#28]
I would suggest that we follow a model similar to [this](https://gist.github.com/digitaljhelms/4287848) with:

* stable/release branch - always current released version (that is on cran/in submission) 
* ~~master~~ main - latest version with newest features etc, (but not with in progress code, should be runnable as is) 
* development/feature branches e.g. "formula" for integrating the new formula system or "restructure" for the new .R file structure etc. we could use prefixes as shown in the linked document but I think that is unnecessary with the size of this project :)

**Comment by kgoldfeld** [comment]
This sounds reasonable. In the current structure, is master the release/stable version - would I rename master to release, and we would create a main branch off that? Or does master become main, and release is an offshoot of main? If so, how does release get updated - when main is ready for release, what exactly is done?

**Comment by assignUser** [comment]
The release (i prefer release over stable as we have distinct releases to cran) branch would be the status of the current master branch at 31.03.20 when you submitted 1.16 to cran.

As we also want to rename the master branch I think it would be easiest to just create two new branches "main" (by "moving" -m master) and "release" of the current master branch.  We can than set main as the default branch, and use it instead of the master branch, when everything is going well after a time we can delete the old master branch. (I did this in my fork to test: https://github.com/assignUser/simstudy )

We could rollback the release branch to 1.16 status, should be relatively easy. 

We would than work on new branches while the task we are working on is unfinished e.g. creating the truncated distributions, once that is done and working we create a pull request from the "truncated-distribution" branch into the main branch,

The release branch would be update via pull request from main once we submit a new version to cran.

This image from the linked most shows it pretty well I think (ignore the hotfix branch, I don't think we need that): 
![image](https://user-images.githubusercontent.com/16141871/89542464-01cc7e80-d800-11ea-8f4c-df2c3ba6c08b.png)

**Comment by kgoldfeld** [comment]
Do you suggest that I do this locally and then push to the remote site? Or should I do it on github?

**Comment by assignUser** [comment]
I don't think you can do any of that on github (except making main the  new default, that is only possible on github) here is a "guide" https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx
I can take care of the release and development branches if you'd like :)

**Comment by assignUser** [comment]
Done, you only need to change the default branch to main: 
![image](https://user-images.githubusercontent.com/16141871/89567262-a4e1c000-d821-11ea-96d8-ff25938db11f.png)
