### ISSUE TITLE
Release simstudy 0.2.0

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#36]
Prepare for release: 
 
* [x] `devtools::build_readme()` 
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_simstudy.html) 
* [x] `devtools::check(remote = TRUE, manual = TRUE)` 
* [x] `devtools::check_win_devel()` 
* [x] `rhub::check_for_cran()` 
* [x] `rhub::check(platform = 'ubuntu-rchk')` 
* [x] `rhub::check_with_sanitizers()` 
* [x] Update `cran-comments.md` 
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release) 
* [x] Review pkgdown reference index for, e.g., missing topics 
 
Submit to CRAN: 
 
* [x] `usethis::use_version('minor')` 
* [ ] `devtools::submit_cran()` 
* [ ] Approve email 
 
Wait for CRAN... 
 
* [ ] Accepted :tada: 
* [ ] `usethis::use_github_release()` 
* [ ] `usethis::use_dev_version()` 
* [ ] submit to [rweekly](https://github.com/rweekly/rweekly.org)

**Comment by assignUser** [comment]
I have started the rhub checks. @kgoldfeld  can you take a look at the news and let me know if they are ok like that: https://github.com/kgoldfeld/simstudy/blob/assignUser/issue19/NEWS.md

**Comment by kgoldfeld** [comment]
Make two changes for typos:

The new function genMixFormula generates mixture formulas from different inputs. [_was Inputs_]
Some simstudy functions now produce [_was produces_] custom errors and warnings. Eventually all conditions will be replaced by the new system to make error handling easier for the user.

**Comment by kgoldfeld** [comment]
I know you did all the checks, but for old times sake, I just my submission script, which includes some of those checks. I'm getting this note from  https://win-builder.r-project.org/1f26yx80tWt6/00check.log:

Maintainer: 'Keith Goldfeld <Keith.Goldfeld@nyumc.org>'

Found the following (possibly) invalid URLs:
  URL: https://github.com/kgoldfeld/simstudy/dev
    From: DESCRIPTION
          man/simstudy-package.Rd
    Status: 404
    Message: Not Found
  URL: https://kgoldfeld.github.io/simstudy (moved to https://kgoldfeld.github.io/simstudy/)
    From: DESCRIPTION
          man/simstudy-package.Rd
    Status: 200
    Message: OK

How should I handle?

**Comment by assignUser** [comment]
Huh, yeah that is indeed wrong, I meant to add the dev version of the
pkgdown site but duplicated the wrong link. Please fix / remove that from
the description sorry.

I wonder why this did not pop up on my end ...

kgoldfeld <notifications@github.com> schrieb am Di., 6. Okt. 2020, 04:57:

**Comment by kgoldfeld** [comment]
So, I am looking for the guilty link in R/simstudy-package.R and not finding it. I am obviously looking in the wrong file - where should I edit?

**Comment by assignUser** [comment]
In the Description under URL: 
```r
URL: https://kgoldfeld.github.io/simstudy,
     https://github.com/kgoldfeld/simstudy,
     https://github.com/kgoldfeld/simstudy/dev
```
where it should of course be:
```r
URL: https://kgoldfeld.github.io/simstudy,
     https://kgoldfeld.github.io/simstudy/dev,
     https://github.com/kgoldfeld/simstudy,

```

**Comment by kgoldfeld** [comment]
Submitted 10/6/2020
