### ISSUE TITLE
Testing of random/statistical functions

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#39]
My goal is to cover each function we work on during other issues (like #23 ) with tests while fixing these. This is pretty easy for deterministic functions like `trimData` but requires some thought when the function in question has a random element (aka all gen* functions etc.).

The most "basic" way to test these would be to create sample output using a seed, saving the output and during test use the same seed and compare if the function output and sample output are identical. 

I am not in favor of this approach as it limits testing (e.g. just one input. no property based testing, just simple comparison) and does not really do what tests should do. We want to test the API (or behavior) of the function, not it's internals. When we use exact output to check against we bind ourself to the implementation, as any change in the generation function (either on our end or on packages we depend on) would break the test. And we would not know if something is actually wrong with the generated data or if just some other equally valid values where generated.

So I think the best way would be to actually analyse the output for the specified characteristics. Sounds easy enough but at this point I will need your help in some (most? 😁 ) cases. 

For genOrdCat it is easy enough just generate a large number of observations, calculate frequencies and compare to the baseprobs. But for e.g. genCorOrdCat I am not sure what is specifically required to check (in the example you show how to check the baseprobs vs. generated data so thats a start). So it would be great if I could depend on you in these cases to write some code to check for the relevant characteristics of the functions in question (currently: genCorOrdCat) and I will use that code to create proper full-featured tests.

**Comment by kgoldfeld** [comment]
Definitely I can help with that - I was thinking about these issues I started to read about Hedgehog and look at your code. I might be a little slower to respond to this, since I am juggling a bunch of things, though I'll try to prioritize this since we are moving things along.

**Comment by assignUser** [comment]
No worries, just post the code here or in #34 when you have time :)

**Comment by assignUser** [comment]
@kgoldfeld So with the help of your email I worked out the following to test the output of the new genordcat function.
`cdxx_yy` where xx is the rho input to genCorOrdCat and yy is the rho used to create the truMat.

- If we set the base probabilities for all items to the same value we can measure the correlation without additional bias from different distributions. (The inverse should be true for checking the frequencies without bias from correlation)
- We know due to the way the copula method works we will have some information loss and this loss will be higher for higher correlations. We see this in my examples below when we compare 99%til of cs02_02 and cs08_08: `0.685 vs. 0.958 `. Should this be explicitly mentioned in the docs as the generated correlation can be roughly 5-10%/0.05-0.1 different from the intended rho? Or should we silently compensate by adjusting rho?
- we can use these distance values to specify a target accuracy of data generation, e.g. 95% < 1 The question here is how accurate should we be? Is it possible to increase accuracy by using different generation methods? Or is the small difference it not worth the effort.

``` r
library(simstudy)
library(pracma)

baseProbs1 <- matrix(0.25, 5, 4)
baseProbs2 <- matrix(c(
  0.2, 0.1, 0.1, 0.6,
  0.6, 0.2, 0.1, 0.1,
  0.5, 0.2, 0.3, 0,
  0.4, 0.1, 0.4, 0.1,
  0.6, 0.2, 0.2, 0
),
nrow = 5, byrow = TRUE
)

corrs <- function(rho, n, rho2 = 0.8) {
  dT <- genData(n)

  dX <- genCorOrdCat(dT,
    adjVar = NULL, baseprobs = baseProbs1,
    prefix = "q", rho = rho, corstr = "cs"
  )

  cdX <- cor(dX[, -1])
  truMat <- genCorMat(nvars = 5, rep(rho2, 10))
  sum(diag(distmat(cdX, truMat)))
}


cs0_08 <- sapply(1:1000, function(x) corrs(0, 1000))
cs04_08 <- sapply(1:1000, function(x) corrs(0.4, 1000))
cs07_08 <- sapply(1:1000, function(x) corrs(0.7, 1000))
cs08_08 <- sapply(1:1000, function(x) corrs(0.8, 1000))
cs02_03 <- sapply(1:1000, function(x) corrs(0.2, 1000, 0.3))
cs02_02 <- sapply(1:1000, function(x) corrs(0.2, 1000, 0.2))

quantile(cs0_08, probs = c(0, .01, .20, .5, .80, .99, 1))
#>       0%       1%      20%      50%      80%      99%     100% 
#> 7.679209 7.780997 7.923979 8.003599 8.091328 8.225688 8.283075
quantile(cs04_08, probs = c(0, .01, .20, .5, .80, .99, 1))
#>       0%       1%      20%      50%      80%      99%     100% 
#> 4.081955 4.170514 4.394859 4.540413 4.671851 4.879843 4.989687
quantile(cs07_08, probs = c(0, .01, .20, .5, .80, .99, 1))
#>       0%       1%      20%      50%      80%      99%     100% 
#> 1.307249 1.438850 1.620294 1.723543 1.844973 2.015889 2.132900
quantile(cs08_08, probs = c(0, .01, .20, .5, .80, .99, 1))
#>        0%        1%       20%       50%       80%       99%      100% 
#> 0.4051408 0.4784524 0.6307651 0.7259427 0.8067967 0.9588577 1.0587418
quantile(cs02_03, probs = c(0, .01, .20, .5, .80, .99, 1))
#>        0%        1%       20%       50%       80%       99%      100% 
#> 0.8510486 0.9905910 1.1912855 1.2990284 1.4132719 1.6330707 1.7860065
quantile(cs02_02, probs = c(0, .01, .20, .5, .80, .99, 1))
#>         0%         1%        20%        50%        80%        99%       100% 
#> 0.09467738 0.19136495 0.30371907 0.38761579 0.47907422 0.68525701 0.80105799
```

<sup>Created on 2020-09-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by kgoldfeld** [comment]
In general I guess I don't really get exactly how general the tests are going to be - are we using Hedgehog to generate quite different data sets (within some range of course) or are we just testing the same set of assumptions each time (albeit with randomly generated data)?

```
If we set the base probabilities for all items to the same value we can measure the correlation without additional bias from different distributions. (The inverse should be true for checking the frequencies without bias from correlation)
```
Are you referring to the multivariate case here? Are you saying to use rows with the same sets of probabilities? I am not quite getting what you are saying here.

```
We know due to the way the copula method works we will have some information loss and this loss will be higher for higher correlations. We see this in my examples below when we compare 99%til of cs02_02 and cs08_08: 0.685 vs. 0.958 . Should this be explicitly mentioned in the docs as the generated correlation can be roughly 5-10%/0.05-0.1 different from the intended rho? Or should we silently compensate by adjusting rho?
```

Yes, we can mention this issue in the docs for sure. I definitely don't want to compensate rho - not unless we had a principled way to do it, i.e. develop some method that we then published and peer-reviewed. 
    
```
we can use these distance values to specify a target accuracy of data generation, e.g. 95% < 1 The question here is how accurate should we be? Is it possible to increase accuracy by using different generation methods? Or is the small difference it not worth the effort.
```

Well - I am open to using exploring different data generation methods, but that is a much longer term challenge. I actually implemented an improved approach for binary outcomes - I did not see anything comparable for count data or categorical outcomes. These are tricky problems.

That said - I think 95% < 1 could work, or maybe relax even a little bit to 90% < 1 or 80% < 1. And we are only considering one correlation structure here, but there are other options - including AR1 or a custom non-structure correlation matrix (say, based on empirical data). It would be important to know how divergent the generated correlated matrices end up being in these cases as well. Of course, we could choose to test the "cs" assumption only.

**Comment by assignUser** [comment]
Ideally we would test via hedgehog if that is feasible computationally and methodologically, but for now simpler test would be enough for me to make sure that the results are still as  intended after I merge `genOrdCat` and `genCorOrdCat` (almost done btw.).

>Are you referring to the multivariate case here? Are you saying to use rows with the same sets of probabilities? I am not quite getting what you are saying here.

Sorry I might be missing some vocabulary but yes, I mean something like this:
``` r
matrix(0.25, 5, 4)
#>      [,1] [,2] [,3] [,4]
#> [1,] 0.25 0.25 0.25 0.25
#> [2,] 0.25 0.25 0.25 0.25
#> [3,] 0.25 0.25 0.25 0.25
#> [4,] 0.25 0.25 0.25 0.25
#> [5,] 0.25 0.25 0.25 0.25
```
Ok so the second half of the issue sounds very interesting but much longer term and more in your area of expertise than mine. I do think that it would be great to be able to assert the validity of the generated data even for different/custom correlation structures, if we manage to that might be a good occasion for the paper in jstatsoft?. I will add a  reminder to the roadmap project and use the < 1 value for now.

**Comment by kgoldfeld** [comment]
Agreed ...

**Comment by assignUser** [comment]
I will open issues regarding other functions if it is needed.
