### ISSUE TITLE
specifying "id" field for a new data set

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#40]
The current approach to providing a the name for the "id" field is not ideal. It can be done either in the first call to defData or if no definition table is provided in genData, then it can be done there. I would like to think about making this consistent.

```
def <- defData(varname = "x1", dist = "binary", formula = .5, id = "cid")

genData(5, id = "xid")
genData(5, def, id = "xid")
```

**Comment by assignUser** [comment]
The least invasive change I can think of would be to insert a check in genData to only allow the `id =` parameter if no def is given.

**Comment by assignUser** [comment]
Hm this seems to be the case already... just happens silently. Would adding a warning/error when id and def are given be enough? Or what are you thinking abou?

**Comment by assignUser** [comment]
As mentioned in #70 you would rather have it override the previous id field.

**Comment by kgoldfeld** [comment]
At least I am consistent - sorry about that.

**Comment by assignUser** [comment]
No worries :D better to write something down twice than not at all 👍
