### ISSUE TITLE
Vectorize genFactor

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#45]
Issue this etc.
https://github.com/kgoldfeld/simstudy/blob/main/R/generate_data.R#L229-L237

**Comment by assignUser** [comment]
@kgoldfeld Why do you coerce double to integer here?https://github.com/kgoldfeld/simstudy/blob/7ff7a98df4236ed3639d64bb67eb9dd172d4fe20/R/generate_data.R#L238 

It shouldn't be an issue to convert a double column to factor?

**Comment by assignUser** [comment]
Ah of course. `factor` will coerce otherwise... 🤦

**Comment by kgoldfeld** [comment]
Obviously not for now, but the whole system for categorical variables and factors is not well thought out. Not super high on the priority list, but could use some improvement.

But are you good on this now? I just tried to figure out why I did that - but don't recall exactly. I know I was getting some weird behavior and this solved it.

**Comment by assignUser** [comment]
I will add a note to the road map about it :), Yeah I think I m done with the function for now.
