### ISSUE TITLE
Another double-dot feature

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#46]
I am not adding this so that we necessarily think about whether or not it makes before the release of 0.2.0 (maybe this is for 0.3.0). (In general, do we have a list of things that we must complete before 0.2.0 is ready - as opposed to things that might be nice to include?)

The new idea would be to allow for vectors to be included in double-dot notation. Here is a non-vectorized case where it might be nice:

```r
library(simstudy)

size1 <- 2
size2 <- 4

def <- defData(varname = "blksize", 
    formula = "..size1 | .5 + ..size2 | .5", dist = "mixture")
genData(10, def)
#>     id blksize
#>  1:  1       4
#>  2:  2       4
#>  3:  3       4
#>  4:  4       2
#>  5:  5       2
#>  6:  6       2
#>  7:  7       4
#>  8:  8       4
#>  9:  9       4
#> 10: 10       2
```

However, it would be more compact to write as a vector, but obviously, it doesn't work:

```r
sizes <- c(2, 4)

def <- defData(varname = "blksize", 
               formula = "..sizes[1] | .5 + ..sizes[2] | .5", dist = "mixture")
#> Error in .checkMixture(newform): Invalid variable(s): 
#> Probabilities can only be numeric or numeric ..vars (not arrays). See ?distribution
```

**Comment by assignUser** [comment]
There was (probably xD) a reason why I excluded this case and created an error but I can't remember why... I will check it out and test it with the check disabled.

**Comment by kgoldfeld** [comment]
So, I don't mean to keep piling things on before we roll out 0.2.0. Is there a checklist of things we ***must*** do before releasing 0.2.0?

**Comment by assignUser** [comment]
I have created a Milestone for the release which helps to keep track of the different issues. https://github.com/kgoldfeld/simstudy/milestone/1

**Comment by assignUser** [comment]
I added what I think would make sense to do before the release

**Comment by kgoldfeld** [comment]
Perfect. 

I have a general (unrelated) question for you. I noticed in the package help there are now descriptions of the distributions (and some other things that are not functions). Where is the source text for those descriptions?

**Comment by assignUser** [comment]
https://github.com/kgoldfeld/simstudy/blob/main/R/simstudy-package.R

**Comment by kgoldfeld** [comment]
Ah - thanks. 

For some reason, in the help contents, the text after the individual distributions includes a comma. So instead of "mixture" we have "mixture,". And while I know that the pseudorandom distributions are what got you into this thing in the first place, they probably shouldn't be there just yet.

<img width="518" alt="Help with comma" src="https://user-images.githubusercontent.com/5994273/93905934-8e0c0580-fcc9-11ea-8368-3adc2ab18af8.png">

**Comment by assignUser** [comment]
ah those are the aliases, i will remove the comma and pseudorandom stuff on my branch :)

**Comment by assignUser** [comment]
#58
