### ISSUE TITLE
Validate genOrdCat corstr

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#48]
I know this has been merged - but in the future, we should be checking for valid corstr - (which are current "ind", "cs", and "ar1"). Right now, if it isn't one of those, it defaults to "ind", which is fine, but there should be a warning.

_Originally posted by @kgoldfeld in https://github.com/kgoldfeld/simstudy/pull/47#issuecomment-698361814_

**Comment by assignUser** [comment]
A related thing, genOrdCat defaults to `asFactor = TRUE` but genCorOrdCat did not turn the colmns into vectors.
What was the reasoning behind that and should we stick to the genOrdCat default?  I will add a note to the deprecated field.

**Comment by kgoldfeld** [comment]
No reasoning behind that - just an oversight. Stick to the genOrdCat default `asFactor = TRUE`.

**Comment by assignUser** [comment]
ok
