### ISSUE TITLE
double-dot Vignette

### ISSUE THREAD

**Issue by assignUser** [kgoldfeld/simstudy#52]
once #41 #46 are closed: create vignette explaining the new formula system and multi core ability.

**Comment by kgoldfeld** [comment]
I'll likely write the vignette once #59 is done. If it is in time for my next scheduled blog post (October 13th), I will post it there - or some version of it. I will also let folks know that a new release is imminent - if it hasn't already happened yet.

**Comment by kgoldfeld** [comment]
Take a look at the new vignette in the vignette branch. If I have left out anything major (or minor) or anything is not clear, feel free to edit or let me know, and I can edit. (I also found and fixed a small bug in the `updateDef` functions that has been there since I created it.)

**Comment by assignUser** [comment]
Yeah looks nice. I think it shows off the features but in a easy to understand way, power users will see the potential immediately anyway 😁 , I added a missing "in" and put the correct name name of the vignette into the news.

**Comment by kgoldfeld** [comment]
Great - I am merging. 

So, two questions for you

(1) are we just just about ready to submit version 0.2.0? It looks all of our milestones are met.

(2) if we are going to submit to CRAN, I definitely want to make an announcement on my blog, and then introduce the double-dot notation -  I will basically use the vignette. I know that you are careful about releasing your name online, so I was wondering if it would be OK if I mentioned you in the blog post. Let me know - and I will identify you any way you'd like (e.g. name, institutional affiliation, etc.)

**Comment by assignUser** [comment]
1. I'd like to fix the trtAssign bug #19 and look over #50 before we start the release process but other than that I think we are ready 👍 
2. I decided to be public with this account & simstudy as I think it is a worthy pursuit :) So feel free to mention me in anyway you like with the information in the description (ORCID etc.) I am not sure on the etiquette of affiliation. Should we name my institution even though my role there is not related to simstudy?

**Comment by kgoldfeld** [comment]
Sounds great. And I'll use your name but no institutional affiliation.
