### ISSUE TITLE
genData with dist = "categorical" is extremely slow

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#61]
This code is now running very, very, very slow:

```r
d <- defData(varname = "grp", formula = "0.125;0.25;0.375;0.25", dist = "categorical")
genData(100000, d)
```

Under the release version, this is pretty instantaneous. Under development, it takes about 10 seconds. Other distributions seem fine. It doesn't look like you made any changes that would affect this - probably an Rcpp issue.

**Comment by kgoldfeld** [comment]
I did a little more exploration, without any more insight as to where things are getting bogged down. In the first case, I execute the function `.gencat` essentially line by line.

```r
n <- 100000
dfSim <- genData(n)
form <- ".5;.3;.2"

formulas <- simstudy:::.splitFormula(form)
envir = parent.frame()

p <- simstudy:::.evalWith(formulas, simstudy:::.parseDotVars(formulas, envir), dfSim, n)
p <- cbind(p, 1 - rowSums(p))

system.time({x <- .Call('_simstudy_matMultinom', p)})
#>    user  system elapsed 
#>   0.049   0.005   0.027
```

Here is a direct call to the function, which for some reason gets bogged down.

```r
system.time({y <- simstudy:::.gencat(n, formula = form, link = "identity", envir = envir)})
#>    user  system elapsed 
#>  16.994   4.854  23.500
```

Any reason why that would be happening? And all of a sudden - this is not an issue in the current release version.

**Comment by kgoldfeld** [comment]
Could it be related to `envir`? That is the only thing that changed, as far as I can tell.

**Comment by assignUser** [comment]
no its the changes to `.adjustProbs` I did for #43 
namely `assertInRange` which checks if the input values are in the given range (e.g. > 0 in this case). They way I implemented that seems to be... not at all fast 🤣 Sorry. I will fix it.

**Comment by assignUser** [comment]
I will also look into continous benchmarking to notice issues like this quicker.

**Comment by kgoldfeld** [comment]
Thanks so much for resolving that one. It would be great to be able to test for speed generally.
