### ISSUE TITLE
Add trtAssignment as a "distribution" to defData to ease flow?

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#69]
Currently, the treatment assignment process using `trtAssign` breaks the flow of the creation of a data set. Usually there is an outcome variable that is a function of the treatment assignment - so that we need to add a column to the table after the treatment assignment is made.

```r
# Data definitions (requires two definitions for the same data set)

d1 <- defData(varname = "g", formula = ".2;.4;.4", dist = "categorical")
d1 <- defData(d1, varname = "x1", formula = "0;10", dist = "uniform")
d1 <- defData(d1, varname = "x2", formula = "2+.5*2", variance = 3, dist = "normal")

d2 <- defDataAdd(varname = "y", formula = "2 + x2 * 3 + rx*2", variance = 5, dist = "normal")

# Data generation (requires three function calls)

dd <- genData(500, d1)
dd <- trtAssign(dd, strata = "g", grpName = "rx")
dd <- addColumns(d2, dd)
```

What if we added a "trtAssign" distribution to the data def table so that the treatment assignment can be part of a single data generation process? It would look like this:

```r
# Only one data definition

d <- defData(varname = "g", formula = ".2;.4;.4", dist = "categorical")
d <- defData(d, varname = "x1", formula = "0;10", dist = "uniform")
d <- defData(d, varname = "x2", formula = "2+.5*2", variance = 3, dist = "normal")
d <- defData(d, varname = "rx", formula = "1;1", variance = "g", dist = "trtAssign")
d <- defData(d, varname = "y", formula = "2 + x2 * 3 + rx*2", variance = 5, dist = "normal")

# Only one function call to generate the data

dd <- genData(500, d)
```
The formula for trtAssign represents the treatment assignment ratio defaults to "1;1", but could be of any length - so, if it is "1;1;1;2" that would be four groups. The variance parameter represents the stratification. Multiple levels of stratification would be represented as "a;b;c", where a, b, and c are variable names (really need to be categorical or factors). The functionality is exactly as it is in function `trtAssign`.

**Comment by assignUser** [comment]
I see what you mean, makes sense. I will likely have time to look it over at the end of the week.

**Comment by kgoldfeld** [comment]
Should be able to use trtAssign code, or some of it. I guess we would keep trtAssign as well.

**Comment by assignUser** [comment]
This just sparked an idea... we could possibly rework the data definitions / "dist" column to contain not only distributions but rather "modifications" that are applied to the data so: dists, trtAssign, addMissing, user defined functions(#71) .... 
That way the complete data workflow would be contained in the definition and clearly readable, which, as i understood, is a high priority for you.

This would defintely be quite some work but could be of value and as we are considering breaking changes in several different places, it might be a good time to implement such sweeping changes (maybe as simstudy 1.0.0 ?)

**Comment by kgoldfeld** [comment]
I see the appeal of that, though I do have to say I like the current flow of keeping the missing data process different from the underlying (true) data generation process. They are two different processes, so I think I would like to keep them separate. As you know, though, I am very keen on being able to define the randomized treatment assignment in the data definition - that to me is a key part of the underlying data generation process. And the truncation obviously. 

Maybe by excluding the missing data from this will simplify things so that it is not as big a lift once the new `dataDef` arguments are in place.

**Comment by assignUser** [comment]
#71 and #75 both seem relevant!
