### ISSUE TITLE
Question: Generate fixed effects in nested structure given the outcome

### ISSUE THREAD

**Issue by b1azk0** [kgoldfeld/simstudy#7]
Hi,
Is there any chance you could help me out with the following?

Is it possible to add `x1` and `x2` predictors to a dataset storing the outcome `y` with `subject` and `observation` variables defining nesting?

I'm looking for this, because when simulating data I wan't to control the amount of variance in `y` that is specific to  between and within two levels. So that running a NULL model of `lmer(y ~ 1 + (1 | subject))` shows that variances of random intercepts and residuals are for example 1 and 1 - 50/50 ratio (or any other of my choice). This part I know how to do using base R.

What I'm looking for, is a way to extend the null model dataset (leaving `y` as it was) with `x1` and `x2` predictors that can (but don't have to) be measured at different levels (subject level or observation level) but controlling for their correlations and overall effect on `y` - as in running an exemplary model of `lmer(y ~ x1 + x2 + (x1 | subject), data)'.

All the best,
blazej

**Comment by b1azk0** [comment]
Keith, thank you very much for this quick response.
I'll try to make my point more clear.

Say I want to fit a model to my data: `lmer(y ~ x1 + x2 + (x1 | subject), real.data)`. 
Before I run this model I will check what is the ratio of variances in `y` before adding any covariates. 
For this I run `lmer(y~1 + (1|subject), real.data)` and see that e.g. variance of the random intercept is and for the residual it's 1 . 
So I can conclude that there is twice as much variance between subjects than within subjects. **This is important** as I want to define the amount of those two variances beforehand in `sim.data`.

In the next step for `real.data` I would analyse the full model `lmer(y ~ x1 + x2 + (x1 | subject), real.data)` looking at fixed estimates given the random structure.

In the context of `sim.data` I'd like to be able to specify the ratio of between and within subject variance to the `y` and having that define how my covariates will look like (for example both significant, or just one significant, with the random slope or without).

The sequence of generating data is unimportant. In my trial and error approach to writing code I managed to simulate just the null data model and was thinking to add to it covariates.
If it's possible to start with the covariates and still have control over variance component's in the NULL model, that's perfect :)

(please note that I'm no expert in both R and mixed models at the theoretical ground, so I might have mistaken some terms).

**Comment by kgoldfeld** [comment]
I think I understand what you are trying to do. I did create a function that allows you to specify the desired ICC (iccRE) and returns the necessary intercept variance. But, that won’t help you here as you are introducing additional random variables, and the concept of ICC gets a bit murky. So, I see why the trial and error approach might be necessary (thought there is probably a way to improve on that).

That said, you could use simstudy to generate the data you need. Have you given it a try?

**Comment by b1azk0** [comment]
I tried playing with `simstudy` but couldn't think of a way to control the intercept to residual variance. 
Just to be superclear - I inspect the relation of those two at **the null model only**. 
After I add covariates to the model (data is generated before applying any models of course) variance components might be whatever they want.

Do you have any hints on to play with `simstudy` to get me as close as it's possible?

PS. I'm really thankful for your time here!

**Comment by kgoldfeld** [comment]
If you send me your code, I may be able to see what you are doing, and I may have time to give it a try … though it may not be today …

**Comment by b1azk0** [comment]
I sent you the code to your nyu mail.
Let me know if it didn't arrive. Thank you

**Comment by assignUser** [comment]
@kgoldfeld Is this issue done? If so you might want to close it 👍
