### ISSUE TITLE
Non-proportional odds assumption for genOrdCat

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#85]
I noticed the problem resolved in Issue #83 in the first place because I need to generate ordinal categorical data without the assumption of proportional cumulative odds, which is what is currently assumed in genOrdCat. I did create a modified function [genOrdCatNP](https://github.com/kgoldfeld/simstudy/blob/non-prop-odds-assumption/R/generate_data.R) in the non-proportional-odds branch (I will start doing it as you do by naming it after an issue).

I set it up as a different function because I am not sure the best way to proceed. I could see just adding it to the current function, Also, the argument names are not final by any means, and obviously would need to add the appropriate checks to these arguments.

I definitely don't want to merge this without your approval and input. If it is not clear exactly what this minor addition is doing, I can explain. Maybe (probably) there is a better way to do this.

I would definitely do a blog entry about this to explain, which we can add to the current vignette. No rush, as I can use this function outside of `simstudy` for now, but just wanted to alert you.

**Comment by assignUser** [comment]
I actually noticed the branch before I saw this issue and had a look around :D 
I would definitely aim to integrate it into genordcat, if this is possible in a clean way.
I will check it out in depth and let you know my thoughts.

**Comment by assignUser** [comment]
At this point in time, I have no idea what you did here and would gladly listen to an explanation of the statistics involved.

**Comment by kgoldfeld** [comment]
I am happy to explain, though I will need to look at it again myself to see if I can figure out what I did. :D

**Comment by assignUser** [comment]
For me, it is more about the statistics as I am not sure I understand what
>  without the assumption of proportional cumulative odds
means :D But knowing how you implemented it can't hurt either.

**Comment by kgoldfeld** [comment]
That I will be able to explain to you - but, to get you started, maybe this [blog](https://www.rdatagen.net/post/2021-01-05-coming-soon-new-feature-to-easily-generate-cumulative-odds-without-proportionality-assumption/) post will help? In that post, there's a link to this [one](https://www.rdatagen.net/post/the-advantage-of-increasing-the-number-of-categories-in-an-ordinal-outcome/) as well that might be useful. But, if you've already seen those and it still doesn't make sense, I can try again.

**Comment by kgoldfeld** [comment]
@assignUser I have implemented the non-proportional option in a new branch. I have also added some unit tests in `test-generate_data`. I will be updating the vignette, and once that is done, you can take a look.
