### ISSUE TITLE
Generate data from correlation matrix with mixed variable types

### ISSUE THREAD

**Issue by Alik-V** [kgoldfeld/simstudy#87]
Hi, thanks for your package!

I am trying to simulate correlated data from a correlation matrix that contains mixed variable types. I have 8 variables with 5 being categorical and 3 numeric ones.

I was trying to do that using genCorGen() but I can only specify distributions for one type of variable at a time, (e.g. binary for categorical or gamma for numeric). 

Is it possible to use my one correlation matrix with 8 variables that would simulate data with mixed distribution types?

**Comment by kgoldfeld** [comment]
Try `genCorFlex()` - that was created to do precisely what you are trying to do.

**Comment by Alik-V** [comment]
Worked beautifully, thanks a lot!

**Comment by Alik-V** [comment]
Sorry to re-open this, but is it possible to use Emrich and Piedmonte algorithm with `genCorFlex()`?

**Comment by kgoldfeld** [comment]
Unfortunately not. The E&P algorithm applies only to binary data, so would not be appropriate in cases where measures with non-binary distributions are included.

**Comment by Alik-V** [comment]
Thank you for the answer!
