### ISSUE TITLE
Variance and dispersion of gamma distribution

### ISSUE THREAD

**Issue by Alik-V** [kgoldfeld/simstudy#90]
Hi, hope you are having a good day and thanks for the package and its ongoing development

I am trying to simulate clinical trial data reported in a publication. The publication itself describes the baseline variables in terms of mean and standard deviation. I wanted to generate some of the numerical variables using gamma distribution, but I was wondering how I could convert the std deviation to dispersion parameter needed for dist="gamma"? Is that possible?

Additional information that I have about the distribution is min, max and percentages of people in different slices of the distribution, i.e. percentage of people having a value between 30-45 etc.

I would appreciate any advice regarding simulating this kind of data

**Comment by kgoldfeld** [comment]
In the [documentation](https://kgoldfeld.github.io/simstudy/articles/simstudy.html), I indicate that the variance <img src="https://render.githubusercontent.com/render/math?math=\sigma^2"> of the gamma distribution is <img src="https://render.githubusercontent.com/render/math?math=d\mu^2">, so you can find the desired *d* based on the known <img src="https://render.githubusercontent.com/render/math?math=\sigma"> and  <img src="https://render.githubusercontent.com/render/math?math=\mu"> as <img src="https://render.githubusercontent.com/render/math?math=d=\sigma/\mu">.

Here are a couple of examples:

```r
library(simstudy)
set.seed(282)

mu <- 100
sigma <- 120

(d <- (sigma/mu)^2)
#> [1] 1.44

d1 <- defData(varname = "g", formula = 100, variance = 1.44, dist = "gamma")
dg1 <- genData(100000, d1)
dg1[, .(mean(g), sd(g))]
#>          V1       V2
#> 1: 99.40462 119.0299

mu <- 50
sigma <- 200

(d <- (sigma/mu)^2)
#> [1] 16

d2 <- defData(varname = "g", formula = 50, variance = 16, dist = "gamma")
dg2 <- genData(100000, d2)
dg2[, .(mean(g), sd(g))]
#>          V1       V2
#> 1: 50.37834 203.9999
```

**Comment by Alik-V** [comment]
Thank you for the detailed help, it worked great!
