### ISSUE TITLE
use genCorData in a loop

### ISSUE THREAD

**Issue by alecristia** [kgoldfeld/simstudy#92]
thanks for a great package!

I'm using it to generate data for meta-analytic & mega-analytic analyses in a test-retest context, with the hope of systematically varying:

1. The effect size of the first day's test (d1)
2. The correlation in performance across days (r)
3. The degree to which different studies vary in d1 and r 

This code works to generate one condition for one study:
```
corlev=.99
C <- matrix(c(1, corlev, corlev, 1), nrow = 2)
dt <- genCorData(100, mu = c(.4, .4), sigma = c(.3, .3), corMatrix = C, cnames=c("pref1","pref2"))
```
So I tried to replace some of those values with variables

```
#establish the range of variation for desiderata 1 (vary effect size on day) & 2 (vary correlation in performance)
myS=c(0,.2,.4) #vary size of day 1 effect via strength of the preference
myR=c(.1,.5,.9) #vary size of correlation across days
# for simplicity,  studies are essentially replications, so desideratum 3 is not yet addressed

dt=NULL
for(thisS in myS){
  for(thisr in myR){
    C <- matrix(c(1, thisr, thisr, 1), nrow = 2)
    for(i in 1:10){ #10 studies
      #generate the data for this study
      temp <- genCorData(100, mu = c(myS, myS), sigma = c(.3, .3), corMatrix = C, cnames=c("pref1","pref2"))
      dt=rbind(dt,
               cbind(i,temp,thisS,thisr))

    }
    
  }
}
```
This yields

> Error in genCorData(100, mu = c(mySs), sigma = c(0.3, 0.3), corMatrix = C,  : 
  Invalid number of variable names

The problem is that myS is interpreted as text, not as a pair of numbers. If you replace `myS,myS` by `0,0` in the `temp <- genCorData...` line, the code runs fine

**Comment by kgoldfeld** [comment]
Alex -


Great to hear you are finding simstudy useful. I've modified your code, but really there is only one key important addition to make it work. You can specify "mu" at each iteration.


library(simstudy)
set.seed(28281)

myS <- c(0,.2,.4) #vary size of day 1 effect via strength of the preference
myR <- c(.1,.5,.9) #vary size of correlation across days

dt <- NULL

for(s in myS) {

  mu <- rep(s, 2)  # <--- this is the key change

  for(r in myR) {

    C <- genCorMat(2, .2)

    for(i in 1:10) { #10 studies

      #generate the data for this study

      temp <- genCorData(100, mu = mu, sigma = c(.3, .3), corMatrix = C,
                         cnames=c("pref1","pref2"))
      dt <- rbind(dt, cbind(s, r, i,temp))

    }
  }
}

dt
#>         s   r  i  id       pref1       pref2
#>    1: 0.0 0.1  1   1 -0.13136158 -0.49624337
#>    2: 0.0 0.1  1   2  0.11263116  0.37004407
#>    3: 0.0 0.1  1   3  0.40508149 -0.08282472
#>    4: 0.0 0.1  1   4  0.05402365  0.16495893
#>    5: 0.0 0.1  1   5  0.24520426  0.48912420
#>   ---
#> 8996: 0.4 0.9 10  96  0.48415631  0.93019895
#> 8997: 0.4 0.9 10  97  0.68497831  0.56121057
#> 8998: 0.4 0.9 10  98  0.46450415 -0.08899113
#> 8999: 0.4 0.9 10  99 -0.20975976  0.04565563
#> 9000: 0.4 0.9 10 100  0.41563930  0.38322460

Created on 2021-03-04 by the reprex package<https://reprex.tidyverse.org/> (v0.3.0)

Let me know if you have any more questions. Take care.


- Keith

________________________________

**Comment by alecristia** [comment]
of course! that makes perfect sense, and I think I saw it in a vignette but didn't make the connection. This works perfectly, thank you!
