### ISSUE TITLE
updateDef does not accept string argument for newvariance

### ISSUE THREAD

**Issue by kgoldfeld** [kgoldfeld/simstudy#93]
updateDef with newvariance as a string returns an error

**Comment by assignUser** [comment]
This seems to be an issue with coercion of data types be dt. It only seems to happen when the previous variance was numeric and the new is character. 

Looking into this I found that this function does not update the definition in place but returns the new one, this goes back to #50  so I guess we keep it this way but I will update the documentation/examples to make clear that you have to reassign the return to get the updated definition :)

**Comment by assignUser** [comment]
We should also rewrite this to use the new assert system but as we also have #65 and #18 going it would make sense to postpone that for now.

**Comment by assignUser** [comment]
This also happens with all elements of the definition if they were initially numeric and the updated is a string. I think the best way to fix this would be to change the type of all def columns to character during creation.
