### ISSUE TITLE
Simulating survival data from existing dataset

### ISSUE THREAD

**Issue by Alik-V** [kgoldfeld/simstudy#94]
Hi, thanks a lot for this brilliant package, been using it for a while to generate correlated data!

Nowadays, I am trying to simulate survival data using some existing dataset, however I am not too sure where to get appropriate formulas to follow an example described in the [documentation](https://kgoldfeld.github.io/simstudy/articles/survival.html). 

```r
library(flexsurv)
# some dummy data
df <- tibble(id = 1:50,
       arm = sample(c(TRUE, FALSE), 50, replace = TRUE),
       history_1 = sample(c(TRUE, FALSE), 50, replace = TRUE),
       numeric_1 = runif(50, min = 100, max = 500),
       outcome_time = runif(50, min = 0, max = 500),
       outcome_event = sample(c(0, 1), 50, replace = TRUE)
       )
# fitting survival model
fit <-
  flexsurvreg(
    Surv(outcome_time, outcome_event) ~ arm + history_1 + numeric_1,
    data = df,
    dist = "weibull"
  )
fit
```
```
Call:
flexsurvreg(formula = Surv(outcome_time, outcome_event) ~ arm + 
    history_1 + numeric_1, data = df, dist = "weibull")

Estimates: 
               data mean  est        L95%       U95%       se         exp(est) 
shape                 NA   1.96e+00   1.34e+00   2.86e+00   3.78e-01         NA
scale                 NA   4.84e+02   2.34e+02   1.00e+03   1.80e+02         NA
armTRUE         5.20e-01   1.91e-01  -2.36e-01   6.17e-01   2.18e-01   1.21e+00
history_1TRUE   5.80e-01   5.31e-02  -3.88e-01   4.94e-01   2.25e-01   1.05e+00
numeric_1       3.18e+02  -7.30e-04  -2.48e-03   1.02e-03   8.91e-04   9.99e-01
               L95%       U95%     
shape                 NA         NA
scale                 NA         NA
armTRUE         7.90e-01   1.85e+00
history_1TRUE   6.79e-01   1.64e+00
numeric_1       9.98e-01   1.00e+00

N = 50,  Events: 24,  Censored: 26
Total time at risk: 13556.47
Log-likelihood = -169.9336, df = 5
AIC = 349.8672
```
Assuming I have already simulated the baseline variables, is the following approach correct to simulate survival outcomes? 
```r
sdef <- defSurv(
  varname = "outcome_time",
  formula = "1.91e-01*arm + 5.31e-02*history_1 + -7.30e-04*numeric_1",
  scale = "4.84e+02",
  shape = "1.96e+00"
)
```
How would I approach getting censorTime definition from my existing data?

Sorry if the questions are basic, I am not quite well-versed in survival analysis. Thank you!

**Comment by kgoldfeld** [comment]
Alik -

Thanks for your comment. I need to investigate `defSurv` and `genSurv` because I don't think it is behaving the way it should. Another way of putting it is that it is a little buggy.

In theory, you could reverse the model to estimate the times to censoring to get the censoring parameters from your data set. And then use those to generate censoring times.

I know you probably don't have time to wait, but I will make this a priority to figure out what is going on. It make take a little while, though.

Thanks.

**Comment by kgoldfeld** [comment]
I have finally checked the code - it is working as expected. I did edit the vignette to include parameter estimation.
